FROM kalilinux/kali-rolling
ARG BUILD_DATE
ARG VERSION
ARG VCS_URL
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.version=$VERSION \
      org.label-schema.name='Kali Linux' \
      org.label-schema.description='Official Kali Linux docker image' \
      org.label-schema.usage='https://www.kali.org/news/official-kali-linux-docker-images/' \
      org.label-schema.url='https://www.kali.org/' \
      org.label-schema.vendor='Offensive Security' \
      org.label-schema.schema-version='1.0' \
      org.label-schema.docker.cmd='docker run --rm kalilinux/kali-linux-docker' \
      org.label-schema.docker.cmd.devel='docker run --rm -ti kalilinux/kali-linux-docker' \
      org.label-schema.docker.debug='docker logs $CONTAINER' \
      io.github.offensive-security.docker.dockerfile="Dockerfile" \
      io.github.offensive-security.license="GPLv3" \
      MAINTAINER="Steev Klimaszewski <steev@kali.org>"
RUN echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && \
    echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
ENV DEBIAN_FRONTEND noninteractive \
  BUNDLE_GEMFILE=/backpack/Gemfile \
  BUNDLE_JOBS=2 \
  BUNDLE_PATH=/backpack \
  GEM_PATH=/backpack \
  GEM_HOME=/backpack
COPY Gemfi* /backpack/
COPY *gemspec /backpack/
RUN set -x \
    && apt-get -yqq update \
    && apt-get -yqq dist-upgrade \
    && apt-get -yqq install apt-utils curl gnupg postgresql postgresql-contrib rubygems ruby-dev > /dev/null \
    && apt-get clean \
    && sleep 1 \
    && service postgresql start \
    && service postgresql status \
    && sleep 1 \
    && gem install bundler --no-rdoc --no-ri \
    && bundle config --global silence_root_warning 1 \
    && sleep 1 \
    && export PATH="$PATH:/backpack" \
    && ls -alh /backpack/ \
    && echo $PATH \
    && cd backpack; bundle install; cd ..
    # this command needs to test for success
    # && msfconsole \
    # && service postgresql restart \
    # && service postgresql status \
    # && ls -alh /opt/metasploit-framework/ \
    # && /opt/metasploit-framework/msfdb init