FROM kalilinux/kali-rolling
MAINTAINER pyramid
ARG BUILD_DATE
ARG VERSION
ARG VCS_URL
ARG VCS_REF
WORKDIR /backpack

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.version=$VERSION \
      org.label-schema.name='Kali Linux' \
      org.label-schema.description='Official Kali Linux docker image' \
      org.label-schema.usage='https://www.kali.org/news/official-kali-linux-docker-images/' \
      org.label-schema.url='https://www.kali.org/' \
      org.label-schema.vendor='Offensive Security' \
      org.label-schema.schema-version='1.0' \
      org.label-schema.docker.cmd='docker run --rm kalilinux/kali-linux-docker' \
      org.label-schema.docker.cmd.devel='docker run --rm -ti kalilinux/kali-linux-docker' \
      org.label-schema.docker.debug='docker logs $CONTAINER' \
      io.github.offensive-security.docker.dockerfile="Dockerfile" \
      io.github.offensive-security.license="GPLv3" \
      MAINTAINER="Steev Klimaszewski <steev@kali.org>"
RUN echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && \
    echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
COPY Gemfi* /backpack/
COPY *gemspec /backpack/
ENV DEBIAN_FRONTEND noninteractive
RUN set -x \
    && apt-get -yqq update \
    && apt-get -yqq dist-upgrade \
    && apt-get -yqq install apt-utils curl gnupg postgresql postgresql-contrib rubygems ruby-dev systemd metasploit-framework > /dev/null \
    && cd /lib/systemd/system/sysinit.target.wants/; for i in ; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; cd ./; done \
    && rm -rf /lib/systemd/system/multi-user.target.wants/; rm -rf /etc/systemd/system/.wants/; rm -rf /lib/systemd/system/local-fs.target.wants/; rm -rf /lib/systemd/system/sockets.target.wants/udev; rm -rf /lib/systemd/system/sockets.target.wants/initctl; rm -rf /lib/systemd/system/basic.target.wants/; rm -f /lib/systemd/system/anaconda.target.wants/* \
    && apt-get clean \
    # && service postgresql start \
    # && service postgresql status \
    # && gem install bundler --no-rdoc --no-ri \
    # && bundle config --global silence_root_warning 1 \
    # && export PATH="$PATH:/backpack" \
    # && echo $PATH \
    # && bundle install \
    # && curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > /backpack/msfinstall > /dev/null \
    # && chmod 755 /backpack/msfinstall \
    # && /backpack/msfinstall \
    && service postgresql restart \
    && service postgresql status \
    && msfdb init